name: Repository Dispatch
on:
  repository_dispatch:
    types: [deploy-check]
jobs:
  fetch-deploy-validation-results:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
    steps:
      - name: "Install node"
        uses: actions/setup-node@v3
        with:
          node-version: '23'
          
      - name: "Install Salesforce CLI"
        run: |
          npm install @salesforce/cli --location=global
          nodeInstallPath=$(npm config get prefix)
          echo "$nodeInstallPath/bin" >> $GITHUB_PATH
          sf --version

      - name: "Populate auth file with SFDX_URL secret of integration org"
        shell: bash
        run: |
          echo ${{ secrets.SFDX_INTEGRATION_URL }} > ./SFDX_INTEGRATION_URL.txt

      - name: "Authenticate to Integration Org"
        run: sf org login sfdx-url -f ./SFDX_INTEGRATION_URL.txt -a integration -s
  
      - name: "Get validation result"
        run: |
          RESULT=$(sf project deploy report --job-id ${{ github.event.client_payload.actionId }} --json)
          echo $RESULT > ./DEPLOY_RESULT.json

      - name: "Build validation errors ouput"
        id: component_errors
        run: |
          if [ "$(jq '.result.details.componentFailures | length' ./DEPLOY_RESULT.json)" -gt 0 ]; then
            FAILURES=$(jq -r '
          "
          ## Component Errors

          | Full Name                | Component Type | Problem                                 | Line | Column |
          |--------------------------|----------------|-----------------------------------------|------|--------|
          " +
              (
                [.result.details.componentFailures[]] |
                map("| \(.fullName) | \(.componentType) | \(.problem) | \(.lineNumber) | \(.columnNumber) |") |\
                join("\n")
              )
            ' ./DEPLOY_RESULT.json)
          fi

          echo "content<<EOF" >> "$GITHUB_OUTPUT"
          echo "$FAILURES" >> "$GITHUB_OUTPUT"
          echo "EOF" >> "$GITHUB_OUTPUT"

      - name: "Build validation successes ouput"
        id: component_successes
        run: |
          if [ "$(jq '[.result.details.componentSuccesses[] | select(.fullName != "package.xml")] | length' ./DEPLOY_RESULT.json)" -gt 0 ]; then
            SUCCESSES=$(jq -r '
          "
          ## Component Successes

          | Full Name                | Component Type |
          |--------------------------|----------------|
          " +
              (
                [.result.details.componentSuccesses[] | select(.fullName != "package.xml")] | 
                map("| \(.fullName) | \(.componentType) |") |
                join("\n")
              )
            ' ./DEPLOY_RESULT.json)
          fi

          echo "content<<EOF" >> "$GITHUB_OUTPUT"
          echo "$SUCCESSES" >> "$GITHUB_OUTPUT"
          echo "EOF" >> "$GITHUB_OUTPUT"

      - name: "Build test errors ouput"
        id: test_errors
        run: |
          if [ "$(jq '.result.details.runTestResult.failures | length' ./DEPLOY_RESULT.json)" -gt 0 ]; then
            TEST_FAILURES=$(jq -r '
          "
          ## Test Errors

          | Class                | Method         | Message                                 | Stack         |
          |----------------------|----------------|-----------------------------------------|---------------|
          " +
              (
                [.result.details.runTestResult.failures[]] |
                map("| \(.name) | \(.methodName) | \(.message) | \(.stackTrace | gsub("\n"; "<br>")) |") |
                join("\n")
              )
            ' ./DEPLOY_RESULT.json)
          fi

          echo "content<<EOF" >> "$GITHUB_OUTPUT"
          echo "$TEST_FAILURES" >> "$GITHUB_OUTPUT"
          echo "EOF" >> "$GITHUB_OUTPUT"

      - name: "Update check run"
        env:
          GH_TOKEN: ${{ github.token }}
          MARKDOWN_CONTENT: |
            # Validation Summary

            ${{ steps.component_errors.outputs.content }}

            ${{ steps.component_successes.outputs.content }}

            ${{ steps.test_errors.outputs.content }}
        run: |
          STATUS=$(jq -r '.result.success | if . then "success" else "failure" end' ./DEPLOY_RESULT.json )
          COMPLETION_DATE=$(jq -r '.result.completedDate' ./DEPLOY_RESULT.json)

          echo "${{ env.MARKDOWN_CONTENT }}" > ./CONTENT.md

          gh api -X PATCH -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          /repos/${{ github.repository }}/check-runs/${{ github.event.client_payload.checkRunId }} \
          -f conclusion=$STATUS \
          -f completed_at=$COMPLETION_DATE \
          -f "output[title]=Validation Results" \
          -F "output[summary]=@CONTENT.md"